### ISSUE TITLE
AdminPanel White Page 

### ISSUE THREAD

**Issue by TheMaintainer** [craiglyoung/yiimp_installation_script#1]
Hi craiglyoung 

I installed yiimp on fresh ubuntu 22.04 
everything installed and worked out of the box except the admin panel 
I even changed it on line 11 but not working only white screen 

/var/web/yaamp/modules/Site/SitControler.php 

http://serverIP/site/AdminPanel

PhpMyAdmin works at http://serverIP/PhpMyAdmin

any ideas !?

**Comment by craiglyoung** [comment]
Hi b2d2dbone

Can you please confirm what the ownership is of /home/pool/yiimp-logs/debug.log ?

If it is owned by pool:www-data, then can you please take a look in it for any errors that it is telling you?  If it isn't owned by pool:www-data, can you please do a sudo chown pool:www-data /home/pool/yiimp-logs/debug.log and see what happens?

Cheers

**Comment by TheMaintainer** [comment]
after executing 
 sudo chown pool www:data /home/pool/yiimp-logs/debug.log 
 
 I get  
 Internal Server Error 
 error_log(home/pool/yiimp-logs/debug.log) Faild to open Stream : permission denied 
 
 I triad to tail the log  
 tail -f  /home/pool/yiimp-logs/debug.log 
  I get 
 front end error 127.0.0.1
 the system is unable to find the requested action "AdminPanel"
 front end error 127.0.0.1
  cWepApp: unable to resolve  the request "AdminPanel"
 
I checked file permission /ownership
$ getfacl /home/pool/yiimp-logs/debug.log
I get
#owner: poo
#group: www-data
#user:: rw -
#group:: r --
#other :: r - -

**Comment by b2d2dbone** [comment]
I checked file permission /ownership 
 
 $  getfacl /home/pool/yiimp-logs/debug.log 
 I get 
 # owner: poo
 # group: www-data
 # user:: rw - 
# group:: r --
#other :: r - -

**Comment by craiglyoung** [comment]
If you're still getting internal server error due to permissions, you will need to make sure that www-data has write access to the file.

The log is telling you that it doesn't know of the action "AdminPanel". Take a look in your /var/web/yaamp/modules/site/SiteController.php file for actionAdminPanel (line 11). You mentioned in your first post that you changed this line, what did you change it to?  If you changed it to something else, then browsing to site/AdminPanel won't work for you, you will need to browse to whatever you changed it to.

**Comment by TheMaintainer** [comment]
I changed it to just admin then revert it back to AdminPanel as it was 
it seems like am not the only one who got this issue 
"https://github.com/cryptopool-builders/Multi-Pool-Installer/issues/8"

**Comment by craiglyoung** [comment]
I have intentionally left 3 options of Yiimp in the installation script so you can change it how you want. Lines 309-311 of install.sh contain the 3 options - you can comment out the one that I use and use one of the other two if you wish, and see if one of those works for you, just make sure that 2 of the 3 are commented out.

I have used this script many times and whenever I have faced that issue, it has been one of three things:
1) Line 11 of SiteController.php is wrong (I forgot what I made my admin panel to be, so the debug.log file told me it couldn't find that action)
2) Permissions were wrong to a log file (I forgot to apply the correct ownership/permissions so nginx couldn't write to the file)
3) memcache or memcache related php packages are missing (something failed and these packages were not installed).

**Comment by craiglyoung** [comment]
> after executing sudo chown pool www:data /home/pool/yiimp-logs/debug.log

Just noticed what you executed, this is wrong.

Should be: sudo chown **pool:www-data** /home/pool/yiimp-logs/debug.log

**Comment by TheMaintainer** [comment]
I executed it correctly  only forgot : here in github
sudo chown pool:www-data /home/pool/yiimp-logs/debug.log

I will reinstall and see how it goes again

**Comment by TheMaintainer** [comment]
Thanks for your work  and support <3
