### ISSUE TITLE
AdminPanel wrong format 

### ISSUE THREAD

**Issue by sp1k36667** [craiglyoung/yiimp_installation_script#2]
![image](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/890df740-2d46-48d8-804d-d3506c4e4077)
and it give no Buttons  looks like css or javascript not working but on the normal Site looks good
![image](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/cd9e2e99-786d-48db-9855-3ffe43a8b29a)

**Comment by craiglyoung** [comment]
There was an issue with what SQL dumps were being imported. Please try this again now.

**Comment by sp1k36667** [comment]
works now thx
