### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sp1k36667** [craiglyoung/yiimp_installation_script#3]
![image](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/f7c00c5f-e16b-4951-ad1a-78a153a08ea8)
by disable Has getinfo in coin add

**Comment by craiglyoung** [comment]
What does it say in your debug.log file? A bit more info would be helpful, thanks.

**Comment by sp1k36667** [comment]
nothing in debug.log but wen you add a new coin and disable the option Has getinfo get this error 

I think it's a bug that has to do with php8.2

error for copy to google "Non-static method ExplorerController::createUrl() cannot be called statically"

[2023-10-15 14:49:58] BackendPricesUpdate
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price bittrex ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price poloniex ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price safecex ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price bleutrade ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price yobit ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price c-cex ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price alcurex ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] BackendPricesUpdateExchange
[2023-10-15 14:49:58] ==== Start Sync Market Price cryptopia ====
[2023-10-15 14:49:58] ==== End Sync Market Price ====
[2023-10-15 14:49:58] ==== END BackendPricesUpdate ====
[2023-10-15 14:49:58] CronjobController::actionRun 3
[2023-10-15 14:51:28] CronjobController::actionRun 4
[2023-10-15 14:52:58] CronjobController::actionRun 5
[2023-10-15 14:54:29] CronjobController::actionRun 6
[2023-10-15 14:55:59] CronjobController::actionRun 7

**Comment by sp1k36667** [comment]
i think i found what wenn u change the numer off the coin in url like /site/coin?id=9 this is nor working to /site/coin?id=6 this is working bur wrong coin

**Comment by craiglyoung** [comment]
I have been able replicate an internal server error when I change coins, though not quite the same as yours. I will take a look and see if I can see what is going on, but perhaps it is php version related.

**Comment by craiglyoung** [comment]
I have manage to fix my error, but I am not sure if it is the same as what you're experiencing. Mine was simply that I didn't put in an RPC Host (on the Daemon tab). As soon as that was filled out, all working fine for me.

If you are still experiencing issues, can you please provide step by step instructions on how to replicate the issue.

**Comment by sp1k36667** [comment]
i will install new instance today then i report

**Comment by sp1k36667** [comment]
Install settings:
Domain Name (no http:// or www. just : example.com or pool.example.com or 185.22.24.26) : xxx.233.162.xxx
Are you using a subdomain (mycryptopool.example.com?) [y/N] : n
Enter support email (e.g. admin@example.com) : admin@example.com
Set Pool to AutoExchange? i.e. mine any coin with BTC address? [y/N] : n
Enter the Public IP of the system you will use to access the admin panel (http://www.whatsmyip.org/) : xxx.233.158.xxx
Install Fail2ban? [Y/n] : n
Install UFW and configure ports? [Y/n] : y
Install LetsEncrypt SSL? IMPORTANT! You MUST have your domain name pointed to this server prior to running the script!! [Y/n]: n

Commands after install:
sudo reboot
cd yiimp_installation_script/utils/
bash delcoin.sh

Add new Coin:
![General](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/ba1e047f-9e2b-40d3-b155-ada5d7ce1574)

![Settings](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/9114723f-36e4-43b4-9128-f312b2a5dfa9)

![Exchange](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/8eb1ca53-a6cf-4766-aa0c-aefa497911d8)

![Daemon](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/d3fa736b-7c23-4f42-a9ff-a68e7a92bcdb)

![Links](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/308a1a7d-7b43-468f-b948-a8803635b41e)

then i click create
![overview](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/6d6e777b-64a7-40a9-82bd-70891a71a895)

now click on the new coin and you get this error

![error](https://github.com/craiglyoung/yiimp_installation_script/assets/141181811/6caab401-51cf-467d-8760-1f13bff8a647)

**Comment by craiglyoung** [comment]
Thanks, I can recreate the issue from that.

It appears to be a Yii issue, perhaps due to php8, in the ExplorerController.php file in the function createUrl. Unfortunately I do not know anything about Yii, so hoping someone else may be able to help out with this. 

In the meantime, it should get you past this problem if you keep your hasgetinfo tickbox enabled.

**Comment by sp1k36667** [comment]
you can test this here

/////////////////////////////////////////////////

// Hide coin id from explorer links... created by createUrl()
public function createUrl($route,$params=array(),$ampersand='&')
{
    if ($route == '/explorer' && isset($params['id'])) {
        $coin = getdbo('db_coins', intval($params['id']));
        if ($coin && $coin->visible && !is_numeric($coin->symbol)) {
            unset($params['id']);
            $route = '/explorer/'.$coin->symbol.'?'.http_build_query($params,'',$ampersand);
            $params = array();
        }
    }

    // Erstelle eine Instanz deines ExplorerController
    $explorerController = new ExplorerController();

    // Verwende die Methode createUrl auf der Instanz
    $url = $explorerController->createUrl($route, $params, $ampersand);

    return $url;
}

/////////////////////////////////////////////////

**Comment by sp1k36667** [comment]
I no longer think it's a problem with the php8 because if I change the ID in the URL it works. I think it's a problem with the DB and it doesn't transfer the information correctly when you change it in the URL
/site/coin/id/6 If you change the id to 8, the same error occurs even though coin id 8 does not exist

**Comment by craiglyoung** [comment]
If I simply change the hasgetinfo DB value for the coin from 1 to 0, it fails for that coin.  Changing it back from 0 to 1 makes it work again. Interesting.

**Comment by craiglyoung** [comment]
Updated the createUrl function to be static - appears to have fixed the issue. Have updated the Yiimp repo to reflect the update.
