### ISSUE TITLE
Stratum compiling

### ISSUE THREAD

**Issue by sp1k36667** [craiglyoung/yiimp_installation_script#4]
The script doesn't manage to compile stratum and this is needed so that the poll runs correctly. 
And the debug screen remains empty

**Comment by sp1k36667** [comment]
I managed to compile it. You still need to add a few things to the install.sh and remove a file
1. remove from yiimp/stratum/sha3/makefile blake2s.c from line 10
2. apt-get install libssh-dev
3. apt-get install libbrotli-dev
4. use this command to compile stratum ```bash gcc -no-pie stratum.o db.o coind.o coind_aux.o coind_template.o coind_submit.o util.o list.o rpc.o job.o job_send.o job_core.o merkle.o share.o socket.o coinbase.o client.o client_submit.o client_core.o client_difficulty.o remote.o remote_template.o user.o object.o json.o base58.o rpc_curl.o iniparser/libiniparser.a algos/libalgos.a sha3/libhash.a -Isecp256k1/include secp256k1/.libs/libsecp256k1.a -lpthread -lgmp -lm -lstdc++ -lssl -lcrypto  -lmysqlclient -O2 `mysql_config --libs` -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lcurl -lnghttp2 -lidn2 -lrtmp -lssh -lpsl -lnettle -lgnutls -lgssapi_krb5 -llber -lldap -llber -lzstd -lbrotlidec -lz -o stratum```

**Comment by craiglyoung** [comment]
Thanks, haven't had a moment to look at this yet, but thanks for your input. I will test it out and update the repo once confirmed it's working.

**Comment by craiglyoung** [comment]
I have reviewed and made changes to the install script and the main Yiimp repo that the script pulls. Thanks for your contribution.
